GroupOne/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from . import settings
admin.site.site_header = settings.ADMIN_SITE_HEADER


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url (r'', include('flashTrolley.urls', namespace='flashTrolley')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flashTrolley/urls.py
from django.conf.urls import patterns, include, url
from flashTrolley.views import home, register, user_login,logout_page, view_product
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
                       url(r'^register/$',register, name='register'),
                       url(r'^$', view_product, name='signin'),
                       url(r'^home/$', home),
                       url(r'^signin/$', user_login),
                       url('', include('social.apps.django_app.urls', namespace='social')),
                       url('', include('django.contrib.auth.urls', namespace='auth')),
                       url(r'^$', 'django.contrib.auth.views.login'),
                       url(r'^logout/$',logout_page),
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # If user is not login it will redirect to login page
                       )

flashTrolley/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField

from django.utils.translation import ugettext_lazy as _


# Create your models here.
class Customer(models.Model):
    username = models.CharField('username', max_length=30)
    fname = models.CharField('First Name', max_length=25)
    lname = models.CharField('Last Name', max_length=25)
    birth_date = models.DateField('Date of Birth')
    phone_number = models.IntegerField('Phone number')
    country = CountryField(blank_label=('Choose country')
    city = models.CharField(max_length=25)
    address = models.CharField(max_length=50)
    email = models.EmailField()
    password = models.CharField(max_length=25)

    def __unicode__(self):
       return '%s %s' %(self.fname, self.lname)


class Product(models.Model):
        product_name = models.CharField(max_length=25)
        product_description = models.TextField()
        product_price = models.FloatField()
        quantity = models.IntegerField()
        expiry_date = models.DateField(blank=True, null=True)
        product_image = models.ImageField(upload_to="flashTrolley/static/images/products")

        def __unicode__(self):
            return '%s' % (self.product_name)

        def getExpiry(self):
            return self.expiry_date

        def getImage(self):
            return self.product_image

        def out_of_stock(self):
            if self.quantity <= 0:
                return "Out of stock"

flashTrolley/forms.py
from django import forms
from .models import Customer
from django_countries.widgets import CountrySelectWidget
from django.forms.extras.widgets import SelectDateWidget
import datetime

class RegistrationForm(forms.ModelForm):
    class Meta:
        this_year = datetime.date.today().year
        yr_choice = []
        for yr in range(1920, int(this_year)):
            yr_choice.append(yr)

        model = Customer
        fields = '__all__'

        widgets = {
            'username': forms.TextInput(),
            'birth_date': SelectDateWidget(years=yr_choice),
            'password': forms.PasswordInput(),
            'country': CountrySelectWidget(),

        }
class SignInForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields=['email','password',]
        widgets={
            'password':forms.PasswordInput(),
        }


    def clean_email(self):
        email=self.cleaned_data.get('email')
        customers=[(customer.email) for customer in Customer.objects.filter(email=email)]
        if not email in customers:
            raise forms.ValidationError("Please first register with us")

        return email

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise  forms.ValidationError("The password is too short, please enter again !!!")

        return password

flashTrolley/views.py
from django.shortcuts import render, redirect
from .models import Customer, Product
from .forms import RegistrationForm, SignInForm
from django.contrib.auth import logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template.context import RequestContext


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/signin')

    else:
        form = RegistrationForm()
    return render(request, 'flashTrolley/register.html', {'register_form': form})


def logout_page(request):
    logout(request)
    return HttpResponseRedirect('/')


def user_login(request):
    if request.method == "POST":
        form = SignInForm(request.POST)
        if form.is_valid():
            return redirect('/')
    else:
        form = SignInForm()
    return render(request, 'flashTrolley/signin.html', {'form': form})

def home(request):
    context = RequestContext(request,
                             {'request': request,
                              'user': request.user})
    return render_to_response('flashTrolley/index.html', context_instance=context)

def view_product(request):
    products=Product.objects.all()
    return render(request, 'flashTrolley/products.html', {'products': products})

templates/flashTrolley/about.html
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title>Fashionpress an E-Commerce online Shopping Category Flat Bootstarp responsive Website Template| About :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Fashionpress Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!-- Custom Theme files -->
<link href="css/style.css" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Lato:100,200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="js/jquery-1.11.1.min.js"></script>
</head>
<body>
<div class="header">
	<div class="header_top">
		<div class="container">
			<div class="logo">
				<a href="index.html"><img src="images/logo.png" alt=""/></a>
			</div>
			<ul class="shopping_grid">
			      <a href="register.html"><li>Join</li></a>
			      <a href="login.html"><li>Sign In</li></a>
			      <a href="#"><li><span class="m_1">Shopping Bag</span>&nbsp;&nbsp;(0) &nbsp;<img src="images/bag.png" alt=""/></li></a>
			      <div class="clearfix"> </div>
			</ul>
		    <div class="clearfix"> </div>
		</div>
	</div>
	<div class="h_menu4"><!-- start h_menu4 -->
		<div class="container">
				<a class="toggleMenu" href="#">Menu</a>
				<ul class="nav">
					<li><a href="index.html" data-hover="Home">Home</a></li>
					<li class="active"><a href="about.html" data-hover="About Us">About Us</a></li>
					<li><a href="contact.html" data-hover="Contact Us">Contact Us</a></li>
					<li><a href="wishlist.html" data-hover="Wish List">Wish List</a></li>
				 </ul>
				 <script type="text/javascript" src="js/nav.js"></script>
	      </div><!-- end h_menu4 -->
     </div>
</div>
<div class="column_center">
  <div class="container">
	<div class="search">
	  <div class="stay">Search Product</div>
	  <div class="stay_right">
		  <input type="text" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}">
		  <input type="submit" value="">
	  </div>
	  <div class="clearfix"> </div>
	</div>
    <div class="clearfix"> </div>
  </div>
</div>
<div class="about">
 <div class="container">
  <div class="about_top">
  	<div class="col-md-4 span1">
  	    <h3>Who We Are</h3>
		<img src="images/p2.jpg" class="img-responsive" alt=""/>
		<h4>Sesequat ante. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce euismod.</h4>
		<p>Aliquam congue fermentum nisl. Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor. Sereque sed dolor. Aliquam.</p>
		<p>Fermentum nisl. Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in.</p>
	</div>
  	<div class="col-md-4 span1 span_2">
  		   <h3>History</h3>
			<h5>2005</h5>
			<p class="m_4">But I must explain to you how all this mistaken idea of denouncing pleasure and praisin</p>
			<h5>2006</h5>
			<p class="m_4">But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system,</p>
			<h5>2012</h5>
			<p class="m_4">But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain</p>
			<h5>2014</h5>
			<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system,</p>
	</div>
  	<div class="col-md-4 span1">
  	       <h3>Opportunities</h3>
			<h4>Sesequat ante. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce euismod.</h4>
			<p>Aliquam congue fermentum nisl. Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor. Sereque sed dolor. Aliquam.</p>
			<p>Fermentum nisl. Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in.</p>
			<h4>Sesequat ante. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce euismod.</h4>
			<p>Aliquam congue fermentum nisl. Mauris accumsan nulla vel diam. Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor. Sereque sed dolor. Aliquam.</p>
	</div>
	<div class="clearfix"> </div>
  </div>  
  <div class="about_bottom">
  	     <div class="col-md-6">
				<h3 class="m_3">Advantages</h3>
				<div class="feature about_box1">
	                    <h4>Ut wisi enim ad minim</h4>
	                    <p>
	                        Lorem ipsum dolor sit amet, vix erat audiam ei. Cum doctus civibus efficiantur in. Nec id tempor imperdiet deterruisset, doctus volumus explicari qui ex, appareat similique an usu.
	                    </p>
	            </div>
	            <div class="feature about_box1">
	                    <h4>Claritas est etiam processus</h4>
	                    <p>
	                        Lorem ipsum dolor sit amet, vix erat audiam ei. Cum doctus civibus efficiantur in. Nec id tempor imperdiet deterruisset, doctus volumus explicari qui ex, appareat similique an usu.
	                    </p>
	            </div>
	        </div>
			<div class="col-md-6 span_3">
				<h3 class="m_3">Testimonials</h3>
				<ul class="about_box span_1">
				  <li class="box_img"><img src="images/p9.jpg" class="img-responsive" alt=""></li>
				  <li class="box_desc">Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram,</li>
				  <h4>Finibus Bonorum <span><a href="#">http://demolink.org</a></span></h4>
				  <div class="clearfix"> </div>
				</ul>
				<ul class="about_box span_1">
				  <li class="box_img"><img src="images/p11.jpg" class="img-responsive" alt=""></li>
				  <li class="box_desc">Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram,</li>
				  <h4>Finibus Bonorum <span><a href="#">http://demolink.org</a></span></h4>
				  <div class="clearfix"> </div>
				</ul>
			</div>
		    <div class="clearfix"> </div>
     </div>
   </div>
  </div>
</div>
<div class="footer_bg">
</div>
<div class="footer">
	<div class="container">
		<div class="col-md-3 f_grid1">
			<h3>About</h3>
			<a href="#"><img src="images/logo.png" alt=""/></a>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
		</div>
		<div class="col-md-3 f_grid1 f_grid2">
			<h3>Follow Us</h3>
			<ul class="social">
				<li><a href=""> <i class="fb"> </i><p class="m_3">Facebook</p><div class="clearfix"> </div></a></li>
			    <li><a href=""><i class="tw"> </i><p class="m_3">Twittter</p><div class="clearfix"> </div></a></li>
				<li><a href=""><i class="google"> </i><p class="m_3">Google</p><div class="clearfix"> </div></a></li>
				<li><a href=""><i class="instagram"> </i><p class="m_3">Instagram</p><div class="clearfix"> </div></a></li>
			</ul>
		</div>
		<div class="col-md-6 f_grid3">
			<h3>Contact Info</h3>
			<ul class="list">
				<li><p>Phone : 1.800.254.5487</p></li>
				<li><p>Fax : 1.800.254.2548</p></li>
				<li><p>Email : <a href="mailto:info(at)fashionpress.com"> info(at)fashionpress.com</a></p></li>
			</ul>
			<ul class="list1">
				<li><p>Aliquam augue a bibendum ipsum diam, semper porttitor libero elit egestas gravida, ut quam, nunc taciti</p></li>
			</ul>
			<div class="clearfix"> </div>
		</div>
	</div>
</div>
<div class="footer_bottom">
       	<div class="container">
       		<div class="cssmenu">
				<ul>
					<li class="active"><a href="login.html">Privacy Policy</a></li> .
					<li><a href="checkout.html">Terms of Service</a></li> .
					<li><a href="checkout.html">Creative Rights Policy</a></li> .
					<li><a href="login.html">Contact Us</a></li> .
					<li><a href="register.html">Support & FAQ</a></li>
				</ul>
			</div>
			<div class="copy">
			    <p>&copy;  2015 Template by <a href="http://w3layouts.com" target="_blank">w3layouts</a></p>
		    </div>
		    <div class="clearfix"> </div>
       	</div>
</div>
</body>
</html>		

templates/flashTrolley/base.html
{% load staticfiles %}

<!DOCTYPE HTML>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Fashionpress Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static "css/bootstrap.css" %}" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

<link href="{% static "css/style.css" %}" rel='stylesheet' type='text/css' />

<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Lato:100,200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="{% static "js/jquery-1.11.1.min.js" %}"></script>
<script src="{% static "js/responsiveslides.min.js" %}"></script>
<script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	nav: true,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
</script>
<script type="text/javascript" src="{% static "js/hover_pack.js" %}"></script>
</head>
<body>
<div class="header">
	<div class="header_top">
		<div class="container">
			<div class="logo">
				<a href="/home/"><img src="{% static "images/word.png" %}" alt=""/></a>
			</div>
			<ul class="shopping_grid">
			      <a href="/register/"><li>Register</li></a>
			      <a href="/signin/"><li>Login</li></a>
			      <a href="#"><li><span class="m_1">Shopping Bag</span>&nbsp;&nbsp;(0) &nbsp;<img src="{% static "images/bag.png" %}" alt=""/></li></a>
			      <div class="clearfix"> </div>
			</ul>
		    <div class="clearfix"> </div>
		</div>
	</div>
	<div class="h_menu4"><!-- start h_menu4 -->
		<div class="container">
				<a class="toggleMenu" href="#">Menu</a>
				<ul class="nav">
					<li class="active"><a href="index.html" data-hover="Home">Home</a></li>
					<li><a href="about.html" data-hover="About Us">About Us</a></li>
					<li><a href="contact.html" data-hover="Contact Us">Contact Us</a></li>
					<li><a href="wishlist.html" data-hover="Wish List">Wish List</a></li>
				 </ul>
				 <script type="text/javascript" src="{% static "js/nav.js" %}"></script>
	      </div><!-- end h_menu4 -->
     </div>
</div>
<!-- slider -->
{% block slider %}{% endblock %}

<!-- search product -->
<div class="column_center">
  <div class="container">
	<div class="search">
	  <div class="stay">Search Product</div>
	  <div class="stay_right">
		  <input type="text" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}">
		  <input type="submit" value="">
	  </div>
	  <div class="clearfix"> </div>
	</div>
    <div class="clearfix"> </div>
  </div>
</div>
<!-- end search product -->

<br/>
<br/>
{% block menu %}{% endblock %}
{% block login %}{% endblock %}
{% block signup %}{% endblock %}
{% block main %}{% endblock %}
<!-- products menu -->
				<!--initiate accordion-->
		<script type="text/javascript">
			$(function() {
			    var menu_ul = $('.menu > li > ul'),
			           menu_a  = $('.menu > li > a');
			    menu_ul.hide();
			    menu_a.click(function(e) {
			        e.preventDefault();
			        if(!$(this).hasClass('active')) {
			            menu_a.removeClass('active');
			            menu_ul.filter(':visible').slideUp('normal');
			            $(this).addClass('active').next().stop(true,true).slideDown('normal');
			        } else {
			            $(this).removeClass('active');
			            $(this).next().stop(true,true).slideUp('normal');
			        }
			    });
			
			});
		</script>
       <!-- side bar -->
       <!-- products -->

<br/>
<br/>

<div class="footer_bg">
</div>
<div class="footer">
	<div class="container">
		<div class="col-md-3 f_grid1">
			<h3>About</h3>
			<a href="#"><img src="{% static "images/logo.jpg" %}" alt=""/></a>
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
		</div>
		<div class="col-md-3 f_grid1 f_grid2">
			<h3>Follow Us</h3>
			<ul class="social">
				<li><a href=""> <i class="fb"> </i><p class="m_3">Facebook</p><div class="clearfix"> </div></a></li>
			    <li><a href=""><i class="tw"> </i><p class="m_3">Twittter</p><div class="clearfix"> </div></a></li>
				<li><a href=""><i class="google"> </i><p class="m_3">Google</p><div class="clearfix"> </div></a></li>
				<li><a href=""><i class="instagram"> </i><p class="m_3">Instagram</p><div class="clearfix"> </div></a></li>
			</ul>
		</div>
		<div class="col-md-6 f_grid3">
			<h3>Contact Info</h3>
			<ul class="list">
				<li><p>Phone : 1.800.254.5487</p></li>
				<li><p>Fax : 1.800.254.2548</p></li>
				<li><p>Email : <a href="mailto:info(at)flashtrolley.com"> info(at)flash-Trolley.com</a></p></li>
			</ul>
			<ul class="list1">
				<li><p>Aliquam augue a bibendum ipsum diam, semper porttitor libero elit egestas gravida, ut quam, nunc taciti</p></li>
			</ul>
			<div class="clearfix"> </div>
		</div>
	</div>
</div>
<div class="footer_bottom">
       	<div class="container">
       		<div class="cssmenu">
				<ul>
					<li class="active"><a href="#">Privacy Policy</a></li> .
					<li><a href="#">Terms of Service</a></li> .
					<li><a href="#">Creative Rights Policy</a></li> .
					<li><a href="#">Contact Us</a></li> .
					<li><a href="register.html">Support & FAQ</a></li>
				</ul>
			</div>
			<div class="copy">
			    <p>&copy;  2015 Flash-Trolley </p>
		    </div>
		    <div class="clearfix"> </div>
       	</div>
</div>
</body>
</html>		

templates/flashTrolley/products.html
    {% load staticfiles %}
    <p>Welcome {{ user.username }} !!</p>

    <a href="/signin/">Login</a>
    <br/>
    <a href="{%  url 'flashTrolley:register' %}">Signup</a>
    {% for product in products %}
        <h2>{{ product }}</h2>
        {{ product.product_description }}<br>
        {{ product.expiry_date }}<br>
        <p><img src="flashTrolley/static/images/products/{{ product.product_image  }}" width="200"/></p>

        {{ product.product_image  }}
    {% endfor %}

templates/flashTrolley/register.html
{% extends 'flashTrolley/base.html' %}

{% block title %} Login | Flash-Trolley {% endblock %}
{% block signup %}
<div class="about">
  <div class="container">
      <div class="register">
          <form method="POST" action="">
                {% csrf_token %}
                {% for field in register_form %}
                    {% if field.errors %}
                        <ol class="errorlist">
                            {% for error in field.errors %}
                                <li><strong>*{{ error|escape }}</strong></li>
                            {% endfor %}
                        </ol>
                    {% endif %}
                    {{ field.label_tag }}
                    {{ field }}<br><br>
                {% endfor %}
                <button type='submit'> Submit </button>
            </form>
            <div class="clearfix"> </div>

		   </div>
	</div>
</div>




{% endblock %}

templates/flashTrolley/signin.html
{% extends 'flashTrolley/base.html' %}

{% block title %} Login | Flash-Trolley {% endblock %}
{% block login %}
  <div class="container">
         <div class="register">
			   <div class="col-md-6 login-left">
			  	 <h3>NEW CUSTOMERS</h3>
				 <p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
				 <a class="acount-btn" href='/register/'>Create an Account</a>
			   </div>
			   <div class="col-md-6 login-right">
			  	<h3>REGISTERED CUSTOMERS</h3>
				<p>If you have an account with us, please log in.</p>

        <form method="POST" action="">
            {% csrf_token %}
            {% for field in form %}
                {% if field.errors %}
                    <ol class="errorlist">
                        {% for error in field.errors %}
                            <li><strong>*{{ error|escape }}</strong></li>
                        {% endfor %}
                    </ol>
                {% endif %}
                <table border="0">
                    <tr>
                        <th style="color: #cc7832">{{ field.label_tag }}</th>
                        <td> {{ field }}</td>
                    </tr>
                </table>
                <br/>
                {% endfor %}
            <button type='submit' class="acount-btn"> Login </button>
        </form>

       <p> Or login with.... </p>
        <a href="{% url 'flashTrolley:social:begin' 'facebook' %}?next={{ request.path }}">Facebook</a>
        <a href="{% url 'flashTrolley:social:begin' 'twitter' %}?next={{ request.path }}">Twitter</a>

			   </div>
			   <div class="clearfix"> </div>
		</div>
	</div>
</div>
{% endblock %}